rustic-ai/rustic-ui-components

docs/quickStart.stories.mdx
- CSS styles are not applied automatically.
- Add a step to the Quick Start documentation for adding the component styling.
=> docs: add step for adding styles in quick start

.storybook/preview.js, docs/theme.stories.mdx, src/components/index.ts, src/components/navBar/navBar.tsx, src/rusticTheme.ts
- Add MUI dark theme
- Add theme toggle to storybook
- Update theme documentation
- Use `useTheme()` in navbar
=> feat: add dark theme

src/components/image/image.css, src/components/image/image.cy.tsx, src/components/image/image.stories.tsx, src/components/image/image.tsx
- Remove default props for `width` and `height`.
- Make it so that if neither `width` nor `height` props are provided, the image takes up the full width of the parent container.
=> feat(image): make responsive

.storybook/preview.js, src/components/messageCanvas/messageCanvas.stories.tsx
- Display functions properly in storybook
- Use ElementRenderer in MessageCanvas's stories
- Add copy example for MessageCanvas
=> docs: display functions properly in storybook, add copy example

src/components/codeSnippet/codeSnippet.stories.tsx, src/components/codeSnippet/codeSnippet.tsx, src/components/messageCanvas/messageCanvas.cy.tsx, src/components/messageCanvas/messageCanvas.stories.tsx, src/components/messageCanvas/messageCanvas.tsx, src/components/messageSpace/messageSpace.stories.tsx, src/components/video/youtubeVideo.cy.tsx
- fix `youtubeVideo` test with incorrect assertion
- remove redundant assertions in `youtubeVideo` tests
- fix import statements for `codeSnippet`, `messageSpace`, and `messageCanvas` files
- remove unused imports in `codeSnippet` and `messageCanvas` files
- condense tests for `messageCanvas`
=> fix: tests and imports

.storybook/preview.js, src/components/messageCanvas/messageCanvas.stories.tsx
This reverts commit bddaaee01b145b0ffd19aef8de9968e16055ddab.
This breaks existing functionality which makes it easy for users to copy code from the docs
=> revert: "docs: display code properly, add copy example"

src/rusticTheme.ts
- add missing text primary color to theme
=> fix: add missing text primary color to theme

src/components/participantsContainer/participantsContainer.stories.tsx
- remove the bulletpoint from the "Note:" in the Storybook description to maintain consistency with other descriptions containing a "Note:"
=> docs(participantsContainer): remove bulletpoint from description

package-lock.json, package.json, src/components/messageCanvas/messageCanvas.css, src/components/messageCanvas/messageCanvas.cy.tsx, src/components/messageCanvas/messageCanvas.stories.tsx, src/components/messageCanvas/messageCanvas.tsx, src/components/messageSpace/messageSpace.stories.tsx, src/components/messageSpace/messageSpace.tsx, tsconfig.json
- Add sender icon
- Update the styling to match design (Time is shown on hover on desktop and on click on mobile)
- `cypress-real-events` is installed to check hover effect on cypress.
=> feat: add sender icon and update styling

README.md
- Add the link for Figma Component Library to README
=> docs: add figma link

src/components/messageSpace/messageSpace.stories.tsx
- Update image in MessageSpace's story to match Figma design
=> docs: update image to match design

docs/troubleshotting.stories.mdx, package-lock.json, src/components/codeSnippet/codeSnippet.stories.tsx
- Add troubleshooting doc
- Add missing @codemirror/language to lock file (generated by npm i)
I'm thinking we could group issues later after we have more questions/answers.
=> docs: add troubleshooting doc

src/components/tooltip/tooltip.stories.tsx, src/rusticTheme.ts
- Add tooltip component 
- Add its stories and tests
=> feat: add tooltip customization to theme file

src/components/table/table.cy.tsx, src/components/table/table.stories.tsx, src/components/table/table.tsx
- Handle empty array in table component
- Add test and story
=> fix: handle empty array in table component

src/components/table/table.cy.tsx, src/components/table/table.stories.tsx, src/components/table/table.tsx
Resolves #39, resolves #38
- Use headers to map table rows if headers props is available.  The order of columns could be changed using headers props now
- Add related stories and tests
Note: This PR will temporarily break the functionality of adding custom labels for headers. Will address this in a follow-up PR
Without headers props
With headers props
Without headers props
With headers props
Change order
=> fix: table shows incorrect data

src/components/codeSnippet/codeSnippet.stories.tsx
- add space between name
- turn "CodeSnippet" into `CodeSnippet` in description for consistency
=> docs(codeSnippet): update title and description for consistency

src/components/textInput/textInput.stories.tsx
- change `WebSocketClients` to `WebSocketClient` in ws prop description and remove incorrect use of colon
=> docs(textInput): update incorrect description for ws prop

src/components/textInput/textInput.css, src/components/textInput/textInput.tsx
- move the send button outside of the input to match the [Figma design](https://www.figma.com/file/dzsbmMmPLRR4EFVPZF7F8i/Rustic-UI---Component-Library?node-id=967%3A3737&mode=dev)
=> feat(textInput): move position of send button

.storybook/preview.js
- Update the background color for component's parent container
Light mode in the story file
Dark mode in the story file
Light mode in the docs file
Dark mode in the docs file
=> docs: update storybook's background color

src/rusticTheme.ts
- Add common/black and white colors (Design system has been updated. Need common colors that won't changed when switching between light mode and dark mode. Will be used in the video component.)
- Create baseTheme first, then create light and dark theme
- Define some color variables for colors that appear more than once
##Screenshots (no changes)
=> fix: add missing theme colors

src/components/menu/popoverMenu.tsx, src/rusticTheme.ts
- Popup menu didn't show the dark mode background color correctively before. This PR hides Mui's default background image to show background color properly
- Update theme based on design (minor color changes)
=> fix: menu background color and update theme

src/components/messageSpace/messageSpace.css, src/components/messageSpace/messageSpace.cy.tsx, src/components/messageSpace/messageSpace.stories.tsx, src/components/messageSpace/messageSpace.tsx
- Add `getProfileComponent` props to `MessageSpace`. This props is used in `MessageCanvas`
=> fix: add missing props to MessageSpace

src/components/textInput/textInput.css, src/components/textInput/textInput.stories.tsx, src/components/textInput/textInput.tsx, src/rusticTheme.ts
- update styles to match [Figma design](https://www.figma.com/file/dzsbmMmPLRR4EFVPZF7F8i/Rustic-UI---Component-Library?type=design&node-id=967-3737&mode=design&t=qz9MesECgLOiR2t8-0)
- add `placeholder` prop
- make `label` prop optional
- update prop descriptions to distinguish between `label` and `placeholder`- the prop description of `label` used the word "placeholder" to describe this functionality
- update theme typography
- change font weight of `body1`
=> feat: update component to match Figma design and update theme

docs/quickStart.stories.mdx
- add section about using Material Symbols
- add new components to `supportElements` example in step 4
=> docs: update quick start doc

src/components/chart/rechartsTimeSeries.tsx
- Update tooltip and axis colors in time series (Tooltip was not shown properly and axes color didn't have enough contrast with the background color in the dark theme)
=> fix: tooltip and axis colors in time series

.storybook/preview.js
- Had a warning on storybook before (See below). Fixed by removing the unnecessary default theme config. Change `defaultViewport: DEFAULT_VIEWPORT,` to `...DEFAULT_VIEWPORT,` would also fixed the problem, but `responsive` is the default value for `defaultViewport` so there's no need to set it again. Reference: https://storybook.js.org/docs/essentials/viewport
=> docs: remove unnecessary config

src/components/map/openLayersMap.stories.tsx, src/components/menu/popoverMenu.stories.tsx, src/components/messageSpace/messageSpace.stories.tsx
- update `OpenLayersMap` storybook description to remove parts that are no longer relevant
- update prop descriptions for consistency
=> docs: update descriptions for relevancy and consistency

src/components/media/audio/sound.css
- make play pause button bigger on mobile
=> feat(sound): make play pause button bigger on mobile

src/components/media/controls/videoControls.tsx
- fix bug regarding attempting to enter fullscreen after exiting fullscreen with `esc`
*To be rebased and merged after PR #80
=> fix: exit fullscreen bug when pressing esc

src/components/media/controls/commonControls.tsx, src/components/media/controls/mediaIconButton.tsx
- add tooltip to media control buttons
=> feat: add tooltip to media control buttons

global.d.ts, package-lock.json, package.json, src/components/textInput/textInput.css, src/components/textInput/textInput.cy.tsx, src/components/textInput/textInput.stories.tsx, src/components/textInput/textInput.tsx, tsconfig.json
- add speech-to-text functionality to the `TextInput` component
=> feat(textInput): add speech-to-text functionality

src/components/media/video/video.stories.tsx
- add max width to stories so they don't take up large screen width when viewing individually
- change captions width to max width
=> docs(video): update storybook

docs/quickStart.stories.mdx, docs/theme.stories.mdx, package-lock.json, package.json, src/components/chart/rechartsTimeSeries.tsx, src/components/icon.tsx, src/components/map/openLayersMap.css, src/components/map/openLayersMap.cy.tsx, src/components/map/openLayersMap.tsx, src/components/media/controls/commonControls.tsx, src/components/media/controls/mediaIconButton.tsx, src/components/menu/popoverMenu.cy.tsx, src/components/menu/popoverMenu.stories.tsx, src/components/menu/popoverMenu.tsx, src/components/messageCanvas/messageCanvas.cy.tsx, src/components/messageCanvas/messageCanvas.stories.tsx, src/components/messageSpace/messageSpace.cy.tsx, src/components/messageSpace/messageSpace.stories.tsx, src/components/navBar/navBar.cy.tsx, src/components/navBar/navBar.stories.tsx, src/components/participantsContainer/participantsContainer.cy.tsx, src/components/participantsContainer/participantsContainer.tsx, src/components/textInput/textInput.tsx, src/components/tooltip/tooltip.stories.tsx
- Replace MUI icons with material symbols
- Uninstall `@mui/icons-material`
- Update related tests/stories
- Create an Icon component to render material symbols 
Note: some icons look slightly different from what we used before. Screenshots are attached
Could use the outlined version which looks same as before, but we need to add <link> for it. Since other icons are not using the outlined version, I'm wondering if we could use rounded version for this
Looks more rounded than before
The edit and delete icons look a little bit different
The filled area is flipped
The collection icon is more rounded and the chat icon has a shorter line at bottom
=> fix: replace mui icons with material symbols

cypress.config.ts, package-lock.json, package.json
- update cypress config for experimental safari support
Safari is not yet fully supported, but Cypress offers [experimental support](https://docs.cypress.io/guides/guides/launching-browsers#WebKit-Experimental).
=> chore: update cypress config for expirimental safari support

src/components/navBar/navBar.css
Resolves #94 
- Update navbar padding to match design
=> fix: update navbar padding to match design

cypress.d.ts, cypress/support/component.tsx, src/components/media/video/video.cy.tsx
- attempt to fix flaky `should display an error message if entering fullscreen fails on ${viewport} screen` test
- create command for hovering over an element and checking if it's visible
=> test: update video tests

src/components/input/baseInput/baseInput.tsx, src/components/input/multimodal/uploader/uploader.tsx
Resolves #105 
- add tooltips to input icons
=> fix: add tooltips to input icons

src/components/input/multimodal/multimodalInput/multimodalInput.stories.tsx, src/components/input/multimodal/multimodalInput/multimodalInput.tsx, src/components/input/multimodal/uploader/uploader.tsx, src/components/types.ts
- Include file names in the message
Note: The alert is only be shown in the storybook to show the content being sent.
=> fix: include file names in the message

src/components/messageCanvas/messageCanvas.css
- fix alignment of sender info
This PR addresses issue #110.
=> fix(messageCanvas): adjust alignment of sender info

cypress/unit/formatDateAndTime.cy.ts, cypress/unit/formatMessageTimestamp.cy.ts, src/components/helper.ts, src/components/messageCanvas/messageCanvas.cy.tsx, src/components/timestamp/timestamp.stories.tsx
- update timestamp format of `formatDateAndTime` output based on issue #111
- add more stories to `TimeStamp`
=> fix: update timestamp format

src/components/codeSnippet/codeSnippet.css, src/components/codeSnippet/codeSnippet.stories.tsx
- fix responsiveness of storybook compnent
- remove parent container from Python story
- make parent container of HTMLInsideAParentContainer story responsive
Addresses issue #108.
=> fix: responsiveness of codeSnippet

src/components/table/table.css
- make `Table` component responsive and scroll on smaller widths
=> fix(table): responsiveness of table

src/components/navBar/navBar.css
=> fix: update button margin

src/components/multipart/multipart.cy.tsx, src/components/multipart/multipart.stories.tsx, src/components/multipart/multipart.tsx
- allow download of files with urls
This PR assumes a URL is already present. When a user uploads files with the `MultimodalInput`, only file names are included in FileData. A discussion has begun in #131 regarding the best way to handle retrieving file urls upon upload.
=>  feat(multipart): download files

src/components/media/controls/mediaIconButton.tsx, src/components/media/controls/videoControls.tsx, src/components/media/video/video.cy.tsx, src/components/media/video/video.tsx
- update tooltip wording of "picture in picture" to "mini player"
- update naming throughout code for consistency
Addresses issue #113.
=> fix: update picture in picture tooltip wording

src/components/media/controls/commonControls.css, src/components/media/transcript/transcript.css
- update overline text styling in media components
Addresses issue #114.
=> fix: update overline text style

src/components/menu/popoverMenu.css, src/rusticTheme.ts
- override `MuiButton` text transform
- none of the Figma designs use buttons with all uppercase, which is the MUI default for buttons
- remove text transform styling from `PopoverMenu` css
=> fix: override button text transform

src/components/map/openLayersMap.css
resolves #109 
- Use aspect ratio instead of fixed height
Note: In the issue, Renata mentioned the height should be 403px. I've confirmed with her that it's okay to use the aspect ratio.
=> fix: use aspect ratio instead of fixed height

src/components/messageCanvas/messageCanvas.tsx, src/components/messageSpace/messageSpace.tsx
- When new messages come in and it's at the bottom of page, the top part of message will be shown if the message is super long. For streamingMarkdown and streamingText, only the initial part of message will be shown. User needs to click scroll button to read more.
- Avoid showing scroll button when it's scrolling (was flaky before)
=> fix: improve scrolling behaviour

src/components/icon/icon.css, src/components/icon/icon.tsx, src/components/input/baseInput/baseInput.tsx, src/components/map/openLayersMap.tsx, src/components/media/controls/commonControls.tsx, src/components/media/controls/mediaIconButton.tsx, src/components/menu/popoverMenu.cy.tsx, src/components/menu/popoverMenu.stories.tsx, src/components/menu/popoverMenu.tsx, src/components/messageCanvas/actions/copy/copyText.tsx, src/components/messageCanvas/messageCanvas.cy.tsx, src/components/messageCanvas/messageCanvas.stories.tsx, src/components/messageSpace/messageSpace.cy.tsx, src/components/messageSpace/messageSpace.stories.tsx, src/components/messageSpace/messageSpace.tsx, src/components/multipart/multipart.tsx, src/components/participantsContainer/participantsContainer.tsx, src/components/tooltip/tooltip.stories.tsx, src/components/visualization/chart/rechartsTimeSeries.tsx
- make media icon buttons larger
- add utility class for large icons
Addresses issue #95 .
=> fix: make media icon buttons larger

src/components/media/controls/commonControls.tsx
- update media progress bar colours
Addresses issue #96 .
=> fix: update media progress bar colours

src/components/visualization/vegaLiteViz/vegaLiteViz.css, src/components/visualization/vegaLiteViz/vegaLiteViz.tsx
- update tooltip styling
(I didn't found a way to get MUI tooltip padding. It's not set in our theme file and I'm not sure how to get the default theme padding)
=> fix: update tooltip styling

src/components/messageSpace/messageSpace.tsx
- update color of scroll down button
Addresses issue #156.
Will have to look into the how `rusticDarkTheme` aligns with MUI default styles for buttons with both `variant='contained'` and `color='primary'` .
=> fix(messageSpace): update color of scroll down button

src/components/menu/popoverMenu.cy.tsx, src/components/menu/popoverMenu.stories.tsx, src/components/menu/popoverMenu.tsx
- Add `href` and `isFileDownload` and `downloadFileName` to `PopoverMenuItem`
- Update stories and tests
Question: Should I also add `target` to specify where to open the link?
=> feat(popoverMenu): support href

src/components/messageCanvas/messageCanvas.css, src/components/messageCanvas/messageCanvas.cy.tsx, src/components/messageCanvas/messageCanvas.tsx, src/components/timestamp/timestamp.tsx
BREAKING CHANGE: Changes in classnames.
- `rustic-message-actions-container` is now `rustic-message-container`
- `rustic-message-actions-container` is now applied to the message actions, as before it was added to the message content
- remove 'last updated:' next to timestamp
- update styling to match updated design
The message actions on mobile in the design are accessed by clicking/holding the message and having a drawer menu appear. We don't have logic implemented for this yet, so I've moved the message actions to the bottom on mobile.
=> fix!: update messageCanvas styling

src/components/media/transcript/transcript.css, src/components/media/transcript/transcript.tsx
- remove transcript header
Addresses issue #170.
=> fix(transcript): remove transcript header

src/components/menu/popoverMenu.css
- Reduce menu's min-width to avoid having extra space when menu item label is short
=> fix(popoverMenu): reduce menu's min-width

src/components/table/table.css, src/components/table/table.cy.tsx, src/components/table/table.stories.tsx, src/components/table/table.tsx, src/components/types.ts
- add pagination
- update title and description to match design
Will follow up with api calls to account for large data sets.
Addresses issue #173.
=> feat(table): add pagination

src/components/menu/popoverMenu.stories.tsx, src/components/menu/popoverMenu.tsx, src/components/visualization/vegaLiteViz/vegaLiteViz.cy.tsx, src/components/visualization/vegaLiteViz/vegaLiteViz.tsx
Resolves #158 
- Add tooltip for icon button
(I wasn't sure if we want to add a props for tooltip label so I used `ariaLabel` for now)
PopoverMenu example
VegaLite example
=> fix(popoverMenu): add tooltip for icon button

package-lock.json, package.json, src/components/index.ts, src/components/types.ts, src/components/visualization/mermaidViz/mermaidViz.css, src/components/visualization/mermaidViz/mermaidViz.cy.tsx, src/components/visualization/mermaidViz/mermaidViz.stories.tsx, src/components/visualization/mermaidViz/mermaidViz.tsx
- Add `mermaidViz` component
- Add stories and tests for it
=> feat(mermaidViz): add mermaidViz component

src/components/menu/popoverMenu.css, src/components/menu/popoverMenu.stories.tsx, src/components/menu/popoverMenu.tsx
- Fix styling for menu item end decorators
=> fix(PopoverMenu): fix styling

src/rusticTheme.ts
Resolves #172 
- Update theme for table to match design
=> fix(table): update theme to match design

src/components/messageCanvas/messageCanvas.tsx
- update getProfileComponent prop description
=> docs(messageCanvas): update getProfileComponent prop description

src/components/question/question.stories.tsx
- add getProfileComponent to "In Message Space" story
- avoid `Uncaught TypeError: Cannot read properties of undefined (reading 'send')`
=> docs(question): add getProfileComponent to story

src/components/input/baseInput/baseInput.tsx
- Resolve tooltip error in TextInput
=> fix(textInput): resolve console error

src/components/menu/popoverMenu.tsx
- Resolve the console error for `PopoverMenu` component. (Popover menu is a menu on desktop version and a drawer on mobile version. Only menu has the `anchorEl` property so I avoid assigning `anchorEl` to drawer. Reference: https://mui.com/material-ui/api/drawer/)
=> fix(popoverMenu): resolve console error

src/components/visualization/perspectiveViz/perspectiveViz.css, src/components/visualization/perspectiveViz/perspectiveViz.stories.tsx, src/components/visualization/perspectiveViz/perspectiveViz.tsx
- Improve the styling of perspectiveViz component (Some elements are unnecessary and are therefore hidden. Couldn't change the styling of popover menu because it's from html select element)
- min-width is reduced slightly to fit into iphone 6 screen
- Sort props in storybook
=> fix(perspectiveViz): improve styling

src/components/pdfViewer/controlButton/controlButton.tsx, src/components/pdfViewer/pdfViewer.tsx
- Fix flaky test by handle page.render promise (Can't verify if it's still flaky, but I've tried running the tests locally several times and the tests didn't fail)
- Fix tooltip console error
- Fix console error related to TextField. It shouldn't be placed within Typography
=> fix(pdfViewer): resolve console errors

src/components/messageSpace/messageSpace.stories.tsx
- fix agent icon not displaying
=> docs(messageSpace): fix agent icon not displaying

.storybook/preview.js, src/components/input/multimodal/multimodalInput/multimodalInput.stories.tsx, src/components/input/textInput/textInput.stories.tsx, src/components/visualization/perspectiveViz/perspectiveViz.stories.tsx
- sort argTypes table by required props globally
=> docs: sort argTypes table by required

src/components/visualization/chart/rechartsTimeSeries.stories.tsx, src/components/visualization/chart/rechartsTimeSeries.tsx
- use argTypes table to display prop fields
- remove console error
=> docs(rechartsTimeSeries): use argTypes table to display prop fields

docs/quickStart.mdx, src/components/input/textInput/textInput.stories.tsx, src/components/messageSpace/messageSpace.stories.tsx, src/components/question/question.stories.tsx
- show sender object in `MessageSpace` and `Question` components
- update code snippet in Quick Start doc
=> docs: show sender object and update quickstart doc

src/components/input/baseInput/baseInput.tsx
- Fix the tooltip position for send button in the MultimodalInput component
=> fix: tooltip position

src/components/visualization/vegaLiteViz/vegaLiteViz.stories.tsx, src/components/visualization/vegaLiteViz/vegaLiteViz.tsx
- VegaLite does not support word wrap for titles and uses the description solely for commenting purposes. To address the word wrap limitation, both the title and description are now directly rendered outside of VegaLite.
=> fix(vegaliteViz): render spec title and description outside of VegaLite

src/components/messageSpace/messageSpace.tsx
=> docs(messageSpace): fix formatting

src/components/filePreview/filePreview.css, src/components/filePreview/filePreview.tsx, src/components/multipart/multipart.cy.tsx, src/components/multipart/multipart.stories.tsx, src/components/types.ts, src/index.css
- Support pdfViewer for pdf files. PdfViewer will not be opened for other file types. 
- Close button is added
- Update test and storybook
https://github.com/rustic-ai/ui-components/assets/103023797/dc3bdd22-0f29-4a79-bd24-5c021df8f20a
=> fix(multipart): add pdfViewer

src/components/multipart/multipart.tsx, src/components/types.ts
- Move supportedViewers out of MultipartData
=> fix: move supportedViewers out of MultipartData

src/components/elementRenderer/elementRenderer.cy.tsx, src/components/elementRenderer/elementRenderer.tsx, src/components/input/textInput/textInput.stories.tsx, src/components/messageCanvas/actions/action.tsx, src/components/messageCanvas/actions/copy/copyText.tsx, src/components/messageCanvas/actions/textToSpeech/textToSpeech.cy.tsx, src/components/messageCanvas/actions/textToSpeech/textToSpeech.tsx, src/components/messageCanvas/messageCanvas.cy.tsx, src/components/messageCanvas/messageCanvas.stories.tsx, src/components/messageCanvas/messageCanvas.tsx, src/components/messageSpace/messageSpace.cy.tsx, src/components/messageSpace/messageSpace.stories.tsx, src/components/messageSpace/messageSpace.tsx, src/components/mockWebSocket.ts, src/components/promptBuilder/mockWebSocket.ts, src/components/promptBuilder/promptBuilder.cy.tsx, src/components/promptBuilder/promptBuilder.stories.tsx, src/components/promptBuilder/promptBuilder.tsx, src/components/question/question.stories.tsx, src/components/types.ts
- Handle receiving and processing messages in `MessageSpace`
- `props.messages` is used to pass unprocessed messages from the page level. `props.ws.onReceive` is used to receive and handle incoming messages from websocket. Original message and its update messages are combined into a single array and stored in the `chatMessages` (`{[messageId: string]: Message[]})`) for quick data retrieval.  
- Make relevant changes to ElementRenderer
- `Message[]` which contains original message and update messages is passed to `ElementRenderer`. `ElementRenderer` renders component with original message as well as updated data from update messages. 
- Change the type for ws.onReceive from (handler: (event: MessageEvent) => void) => void to onReceive?: (handler: (message: Message) => void) => void. This …
=> fix: update message handling

src/components/input/baseInput/baseInput.css, src/components/input/textInput/textInput.stories.tsx
Addresses issue #236.
- fix positioning of `TextInput` send button
- update `TextInput` story to show longer input
=> fix(textInput): fix positioning of send button

src/components/input/baseInput/baseInput.tsx
Addresses issue #261.
- avoid multiple fetch requests by emoji picker
=> fix(baseInput): avoid multiple fetch requests

src/components/filePreview/filePreview.css, src/components/filePreview/filePreview.tsx, src/components/input/multimodal/multimodalInput/multimodalInput.stories.tsx, src/components/input/multimodal/multimodalInput/multimodalInput.tsx, src/components/input/multimodal/uploader/uploader.tsx, src/components/multipart/multipart.stories.tsx, src/components/multipart/multipart.tsx, src/components/types.ts, src/index.css
- Add `showFullName` props to support showing long names
=> fix: support showing long names

src/components/input/baseInput/baseInput.css, src/components/input/baseInput/baseInput.tsx
- Fix emoji icon position so that its position doesn't change when there are multiple lines of input.
=> fix(input): fix emoji icon position

src/components/visualization/vegaLiteViz/vegaLiteViz.stories.tsx, src/components/visualization/vegaLiteViz/vegaLiteViz.tsx
- Show markdown for description
=> fix(vegalite): render description as markdown

src/components/visualization/perspectiveViz/perspectiveViz.tsx
- Remove perspective version from the installation instruction
=> docs: remove perspective version

src/components/input/multimodal/multimodalInput/multimodalInput.cy.tsx, src/components/input/multimodal/multimodalInput/multimodalInput.stories.tsx, src/components/input/multimodal/multimodalInput/multimodalInput.tsx, src/components/input/multimodal/uploader/uploader.tsx, src/components/types.ts
- Support rendering upload options (Able to add accepted file types, label, icon name and metadata for each option)
- Update tests and storybook
=> fix(input): add popover menu to multimodalInput and uploader

src/components/input/multimodal/multimodalInput/multimodalInput.cy.tsx, src/components/input/multimodal/multimodalInput/multimodalInput.stories.tsx, src/components/input/multimodal/multimodalInput/multimodalInput.tsx, src/components/input/multimodal/uploader/uploader.tsx, src/components/types.ts
- handle 409 uploading error by adding a new function props to fetch existing files and update file name accordingly
- update cypress and storybook
=> fix(uploader): handle 409 error

src/components/types.ts, src/components/visualization/perspectiveViz/perspectiveViz.stories.tsx, src/components/visualization/perspectiveViz/perspectiveViz.tsx
- Support configuring expansionDepth and expandAll for initial render
ExpansionDepth=0
ExpansionDepth=1
ExpansionDepth=2
=> fix: configure expansion depth

src/components/filePreview/filePreview.tsx, src/components/multipart/chatCompletion/chatCompletion.stories.tsx, src/components/multipart/chatCompletion/chatCompletion.tsx, src/components/multipart/multipart/multipart.stories.tsx, src/components/multipart/multipart/multipart.tsx, src/components/pdfViewer/pdfViewer.stories.tsx, src/components/pdfViewer/pdfViewer.tsx, src/components/types.ts
- add getAuthHeaders to file-related components (PDFViewer, ChatCompletion, Multipart)
=> fix: add getAuthHeaders to file-related components

package-lock.json, package.json, src/components/calendar/fCCalendar.tsx, src/components/codeSnippet/codeSnippet.tsx, src/components/dynamicForm/uniformsForm.tsx, src/components/image/image.tsx, src/components/map/openLayersMap.tsx, src/components/markdown/markedMarkdown.css, src/components/markdown/markedMarkdown.tsx, src/components/media/audio/sound.tsx, src/components/media/video/video.tsx, src/components/multipart/chatCompletion/chatCompletion.tsx, src/components/multipart/multipart/multipart.tsx, src/components/question/question.tsx, src/components/table/table.cy.tsx, src/components/table/table.tsx, src/components/text/text.tsx, src/components/visualization/chart/rechartsTimeSeries.tsx, src/components/visualization/mermaidViz/mermaidViz.tsx, src/components/visualization/perspectiveViz/perspectiveViz.cy.tsx, src/components/visualization/perspectiveViz/perspectiveViz.tsx, src/components/visualization/plotlyGraph/plotlyGraph.tsx, src/components/visualization/vegaLiteViz/vegaLiteViz.tsx, src/components/weather/weather.tsx
- Use markdown to display description and text content
- Add title and description to all message formats
- Use body1(16px) for text content/description
=> fix: use markdown to display description and text content

package-lock.json, package.json, src/components/video/youtubeVideo.tsx, src/components/visualization/chart/rechartsTimeSeries.tsx
- Bump the version for release
- Mention Youtube Video and Recharts Time Series Components will be deprecated
=> chore: bump the version for release

src/components/input/baseInput/baseInput.tsx, src/components/input/multimodal/multimodalInput/multimodalInput.cy.tsx, src/components/input/multimodal/multimodalInput/multimodalInput.stories.tsx, src/components/input/multimodal/multimodalInput/multimodalInput.tsx, src/components/input/textInput/textInput.cy.tsx, src/components/input/textInput/textInput.stories.tsx, src/components/input/textInput/textInput.tsx, src/components/sharedDescription.ts
- sent chatCompletion message correctly
- `toChatRequest` was applied twice for `multimodalInput` — once in `baseInput`, and once in `multimodalInput`. I removed `toChatRequest` from `baseInput` and kept the conversion only in `multimodalInput` and `textInput`.
- update tests and storybook
- The way we displayed `textInput` in Storybook was rendering the `baseInput` component, instead of `textInput`. I now render `textInput` directly and reuse the argType descriptions in both `textInput` and `multimodalInput`.
=> fix: sent chatCompletion message correctly

package-lock.json, package.json, src/components/multipart/chatCompletion/chatCompletion.tsx, src/components/multipart/downloadButton.tsx, src/components/multipart/multipart/multipart.tsx
- send headers for file download
=> fix: send headers for file download

src/components/visualization/vegaLiteViz/vegaLiteViz.stories.tsx, src/components/visualization/vegaLiteViz/vegaLiteViz.tsx, src/components/visualization/vegaLiteViz/vegaLiteViz.types.ts
- Support authHeaders for vegaliteViz
=> fix: support authHeaders for vegaliteViz

package-lock.json, package.json, src/components/elementRenderer/elementRenderer.tsx, src/components/index.ts, src/components/messageArchive/index.ts, src/components/messageArchive/messageArchive.css, src/components/messageArchive/messageArchive.cy.tsx, src/components/messageArchive/messageArchive.stories.tsx, src/components/messageArchive/messageArchive.tsx
- add `messageArchive` component to show messages without ws connection
- remove timeSeries example from messageSpace's story
- bump version for release
=> feat: add messageArchive

package-lock.json, package.json, src/components/input/baseInput/baseInput.css, src/components/input/baseInput/baseInput.tsx, src/components/input/multimodal/multimodalInput/multimodalInput.css
- fix textInput styling (Send button doesn't align with other icons. Didn't use background paper color within input box)
I added blue background color for testing purpose. Storybook still shows white background color
=> fix: fix textInput styling

package-lock.json, package.json, src/components/types.ts, src/components/visualization/perspectiveViz/perspectiveViz.stories.tsx, src/components/visualization/perspectiveViz/perspectiveViz.tsx
=> feat(perspective): support date format customization
