- src/components/messageCanvas/messageCanvas.tsx
- src/components/messageSpace/messageSpace.cy.tsx
- src/components/messageSpace/messageSpace.tsx
- src/components/textInput/textInput.cy.tsx
- src/components/textInput/textInput.tsx
- remove unused data-cy attribute from `MessageCanvas` component
- update data-cy attributes for `MessageSpace` and `TextInput` for consistency
> refactor: update data-cy attributes for consistency

- src/components/index.ts
- src/components/menu/popoverMenu.css
- src/components/menu/popoverMenu.cy.tsx
- src/components/menu/popoverMenu.stories.tsx
- src/components/menu/popoverMenu.tsx
- create `PopoverMenu` component
- match mobile view to design
> feat(popoverMenu): create PopoverMenu component

- package-lock.json
- package.json
- src/components/codeSnippet/codeSnippet.stories.tsx
- src/components/codeSnippet/codeSnippet.tsx
* leverage EditorView.dispatch to set language 
* update peerDependencies
* updated docs with note about codemirror dependencies
> fix(codesnippet): fix language highlighting

- src/components/image/image.stories.tsx
- src/components/messageSpace/messageSpace.stories.tsx
- Use relative path for image stories
> docs: use relative path for image stories

- src/components/textInput/textInput.css
- src/components/textInput/textInput.tsx
- update `TextInput` className for consistency/match component name
> refactor(textInput)!: update TextInput className for consistency

- src/components/table/table.cy.tsx
- src/components/table/table.stories.tsx
- src/components/table/table.tsx
- Update headers props to support adding labels and specify the order of columns
- Update related stories and tests
> fix!: update headers props

- src/components/calendar/fCCalendar.stories.tsx
- src/components/menu/popoverMenu.stories.tsx
- src/components/participantsContainer/participantsContainer.stories.tsx
- src/components/table/table.stories.tsx
- remove colons from interface prop descriptions
> docs: remove unnecessary colons from interface prop descriptions

- src/components/chart/rechartsTimeSeries.stories.tsx
- remove unnecessary type exports from RechartsTimeSeries's story file
> refactor: remove unnecessary type exports

- src/components/calendar/fCCalendar.stories.tsx
- src/components/calendar/fCCalendar.tsx
- src/components/codeSnippet/codeSnippet.stories.tsx
- src/components/codeSnippet/codeSnippet.tsx
- src/components/image/image.cy.tsx
- src/components/image/image.stories.tsx
- src/components/image/image.tsx
- src/components/index.ts
- src/components/map/openLayersMap.tsx
- src/components/markdown/markedMarkdown.tsx
- src/components/markdown/markedStreamingMarkdown.tsx
- src/components/messageSpace/messageSpace.cy.tsx
- src/components/messageSpace/messageSpace.stories.tsx
- src/components/messageSpace/messageSpace.tsx
- src/components/table/table.stories.tsx
- src/components/table/table.tsx
- src/components/text/streamingText.tsx
- src/components/text/text.tsx
- src/components/textInput/textInput.stories.tsx
- src/components/textInput/textInput.tsx
- src/components/types.ts
BREAKING CHANGE: MessageProps and other types are updated and renamed.
> feat!: dataformats to implement custom components and/or extend existing components

- src/components/messageSpace/messageSpace.stories.tsx
-  Fix the same key error in the MessageSpace's story
> docs: fix the same key error

- src/components/calendar/fCCalendar.stories.tsx
- update calendar storybook to add a note about initial view
> docs: update calendar storybook

- src/components/media/audio/sound.css
- src/components/media/audio/sound.cy.tsx
- src/components/media/audio/sound.tsx
- src/components/media/video/video.css
- src/components/media/video/video.cy.tsx
- src/components/media/video/video.tsx
- fix bug in `Sound` component where error is mounted but not visible, taking up space
- not as noticeable in `Video` component because of `position: absolute`
> fix: error component taking up space with visibility hidden

- src/rusticTheme.ts
Resolves #92, resolves #93
- Update MUI theme (Typography and colors)
> fix: update mui theme

- src/rusticTheme.ts
Resolves #98 
- update colors to improve overall look and color contrast
> fix: update colors to improve overall look and color contrast

- src/components/messageSpace/messageSpace.stories.tsx
- Add new components to messageSpace's story
> docs: add new components to messageSpace's story

- cypress/support/component.tsx
- update custom Cypress command to fix flaky Video tests
> test: update custom command

- src/components/messageSpace/messageSpace.stories.tsx
- update `messageSpace` story to make responsive
Addresses issue #112.
> docs: messageSpace responsiveness

- src/components/messageSpace/messageSpace.css
- src/components/messageSpace/messageSpace.cy.tsx
- src/components/messageSpace/messageSpace.stories.tsx
- src/components/messageSpace/messageSpace.tsx
- src/rusticTheme.ts
- Show 'go to bottom' button if it's not at the bottom of the messageSpace 
- Scroll to bottom when the page is loaded
- Scroll to bottom automatically if new message comes in and user's viewing the bottom of the MessageSpace. Won't scroll if the last message in the message list is not shown 
Note: Design for button is not finalized yet, so I removed all the button styling changes I added before.
> feat: add scroll-to-bottom

- src/components/messageCanvas/messageCanvas.stories.tsx
- Update sample code for copyText component
> docs: update sample code

- src/components/elementRenderer/elementRenderer.cy.tsx
- src/components/elementRenderer/elementRenderer.tsx
- src/components/index.ts
- src/components/messageCanvas/messageCanvas.stories.tsx
- src/components/messageSpace/messageSpace.cy.tsx
- src/components/messageSpace/messageSpace.stories.tsx
- src/components/messageSpace/messageSpace.tsx
- src/components/question/question.css
- src/components/question/question.cy.tsx
- src/components/question/question.stories.tsx
- src/components/question/question.tsx
- src/components/types.ts
- add question component
Does not yet handle state persistence.
> feat(question): add question component

- src/components/question/question.tsx
- update selected button text color
> fix(question): update selected button text color

- src/components/image/image.stories.tsx
> docs(image): add story for inline svg

- src/components/media/controls/commonControls.tsx
- src/components/media/controls/mediaIconButton.tsx
- src/components/messageCanvas/actions/copy/copyText.tsx
Resolves #171 
- Update tooltip title to capitalize the first letter of first word
> fix(tooltip): update tooltip labels

- cypress/support/variables.ts
- src/components/elementRenderer/elementRenderer.cy.tsx
- src/components/elementRenderer/elementRenderer.tsx
- src/components/input/multimodal/multimodalInput/multimodalInput.cy.tsx
- src/components/input/multimodal/multimodalInput/multimodalInput.stories.tsx
- src/components/input/textInput/textInput.cy.tsx
- src/components/input/textInput/textInput.stories.tsx
- src/components/messageCanvas/actions/copy/copyText.cy.tsx
- src/components/messageCanvas/messageCanvas.cy.tsx
- src/components/messageCanvas/messageCanvas.stories.tsx
- src/components/messageCanvas/messageCanvas.tsx
- src/components/messageSpace/messageSpace.cy.tsx
- src/components/messageSpace/messageSpace.stories.tsx
- src/components/messageSpace/messageSpace.tsx
- src/components/question/question.cy.tsx
- src/components/question/question.stories.tsx
- src/components/types.ts
BREAKING CHANGE: Message.sender is now an object with id and name instead of a plain string. Also renamed Message.topicId to Message.topic
> fix(types)!: define type for Message sender

- src/components/messageCanvas/messageCanvas.stories.tsx
- src/components/messageSpace/messageSpace.stories.tsx
- src/components/pdfViewer/pdfViewer.tsx
- update profile component in messageCanvas and messageSpace to match design
- mention PDF.js in pdfViewer's description
> docs: update profile component and pdfViewer description

- src/components/index.ts
- src/components/input/multimodal/uploader/uploader.tsx
> fix(uploader): expose uploader component

- src/components/participantsContainer/participantsContainer.stories.tsx
- src/components/participantsContainer/participantsContainer.tsx
- Fix console error (ArgTypes in participantsContainer's storybook documentation had a console error. Component itself didn't have any error.)
> docs(participantsContainer): fix console error

- src/components/visualization/perspectiveViz/perspectiveViz.tsx
-update button styling
(Need to update theme to make buttons look good in a follow up)
> fix(perspectiveViz): update button styling

- src/components/input/emoji/emoji.tsx
- Fix the transaction error without adding database.close() logic
> fix(emoji): try fixing flaky test

- src/components/calendar/fCCalendar.stories.tsx
- src/components/calendar/fCCalendar.tsx
- src/components/codeSnippet/codeSnippet.stories.tsx
- src/components/codeSnippet/codeSnippet.tsx
- src/components/image/image.stories.tsx
- src/components/image/image.tsx
- src/components/map/openLayersMap.stories.tsx
- src/components/map/openLayersMap.tsx
- src/components/markdown/markedMarkdown.stories.tsx
- src/components/markdown/markedMarkdown.tsx
- src/components/media/audio/sound.stories.tsx
- src/components/media/audio/sound.tsx
- src/components/media/video/video.stories.tsx
- src/components/media/video/video.tsx
- src/components/menu/popoverMenu.stories.tsx
- src/components/menu/popoverMenu.tsx
- src/components/multipart/multipart.stories.tsx
- src/components/multipart/multipart.tsx
- src/components/participantsContainer/participantsContainer.tsx
- src/components/table/table.stories.tsx
- src/components/table/table.tsx
- src/components/text/text.stories.tsx
- src/components/text/text.tsx
- src/components/timestamp/timestamp.stories.tsx
- src/components/timestamp/timestamp.tsx
- src/components/video/youtubeVideo.stories.tsx
- src/components/video/youtubeVideo.tsx
- src/components/visualization/chart/rechartsTimeSeries.stories.tsx
- src/components/visualization/chart/rechartsTimeSeries.tsx
- Move storybook descriptions to the top of component files
> docs: make descriptions consistent

- src/components/index.ts
- src/components/messageCanvas/actions/index.tsx
- src/components/messageCanvas/actions/textToSpeech/textToSpeech.cy.tsx
- src/components/messageCanvas/actions/textToSpeech/textToSpeech.tsx
- src/components/messageCanvas/messageCanvas.stories.tsx
- Add TextToSpeech (Only read title, description, alt, text for now, Click icon button to play and stop)
- Fix the data-cy conversion in actions/index.tsx
- Add tests and story
> feat(textToSpeech): add text-to-speech feature

- src/components/messageSpace/messageSpace.tsx
- src/components/visualization/perspectiveViz/perspectiveViz.tsx
- src/rusticTheme.ts
- Update theme palette
- Add customized button/chip (I didn't add selected state, because MUI button/chip don't have selected state. We might need to change selected state's color in the component when needed)
(Note: The button/chip usage in the individual component is not updated yet. Design team hasn't integrated the new button styling to all of the components yet. I only updated the Chip in the MessageSpace. I also hasn't added customized icon and button group.)
https://github.com/rustic-ai/ui-components/assets/103023797/e9d59ce4-2313-4a68-8449-2b7685991792
> fix: update theme and add customized button/chip

- src/components/messageCanvas/actions/textToSpeech/textToSpeech.cy.tsx
- src/components/messageCanvas/actions/textToSpeech/textToSpeech.tsx
- src/components/types.ts
- Add visualizationFormat
- Add transcript to the reading list
- Update tests
> fix: add visualizationFormat and read transcript

- package-lock.json
- package.json
- src/components/index.ts
- src/components/promptBuilder/mockWebSocket.ts
- src/components/promptBuilder/promptBuilder.css
- src/components/promptBuilder/promptBuilder.cy.tsx
- src/components/promptBuilder/promptBuilder.stories.tsx
- src/components/promptBuilder/promptBuilder.tsx
- src/components/types.ts
- src/index.css
- add prompt builder component
> feat(promptBuilder): add promptBuilder component

- src/components/question/question.tsx
- src/rusticTheme.ts
> fix(theme): update button colors

- docs/quickStart.mdx
- docs/theme.mdx
- package-lock.json
- package.json
- src/components/calendar/fCCalendar.tsx
- src/components/input/baseInput/baseInput.tsx
- src/components/input/multimodal/multimodalInput/multimodalInput.tsx
- src/components/input/textInput/textInput.tsx
- src/components/map/openLayersMap.tsx
- src/components/markdown/markedMarkdown.tsx
- src/components/pdfViewer/pdfViewer.tsx
- src/components/question/question.tsx
- src/components/text/text.tsx
- src/components/video/youtubeVideo.tsx
- src/components/visualization/chart/rechartsTimeSeries.tsx
- src/components/visualization/mermaidViz/mermaidViz.tsx
- src/components/visualization/perspectiveViz/perspectiveViz.tsx
- src/components/visualization/vegaLiteViz/vegaLiteViz.tsx
- Move component-specific dependencies from dependencies to devDependencies
- Update docs to clarify installation of component-specific dependencies
> fix: move component-specific dependencies

- package-lock.json
- package.json
- src/components/calendar/fCCalendar.css
- src/components/calendar/fCCalendar.cy.tsx
- src/components/calendar/fCCalendar.stories.tsx
- src/components/calendar/fCCalendar.tsx
Addresses issue #249 and some points in issue #235.
- update FullCalendar version
- apply rustic-ui colours
- add time grid to week and day views
> fix(fCCalendar): apply rustic ui styling

- src/components/input/multimodal/multimodalInput/multimodalInput.css
- src/components/input/multimodal/multimodalInput/multimodalInput.tsx
- Adjust border for multimodalInput
> fix(input): adjust border

- src/components/input/baseInput/baseInput.css
- src/components/input/baseInput/baseInput.tsx
- src/components/input/emoji/emoji.tsx
- src/components/input/multimodal/multimodalInput/multimodalInput.tsx
- src/components/input/multimodal/uploader/uploader.tsx
- Update input styling (change button colors, background color, icon alignment)
(Please ignore the border color. It looks weird in the recording)
> fix: update input styling

- src/components/icon/index.ts
- src/components/index.ts
- src/rusticTheme.ts
- Update typography and border radius for buttons
- Expose icon component
> fix: update theme and expose icon component

- src/components/visualization/perspectiveViz/perspectiveViz.tsx
-  Update installation instruction for perspectiveViz
Note: We should upgrade perspective to the latest version later.
> docs(perspectiveViz): update installation instruction

- src/components/input/multimodal/multimodalInput/multimodalInput.cy.tsx
- src/components/input/multimodal/multimodalInput/multimodalInput.stories.tsx
- src/components/input/multimodal/uploader/uploader.tsx
- Update file upload/delete paths to replace placeholder params with actual values. E.g. `fileName`=>actual fie name
> fix(multimodalInput): update file paths

- package-lock.json
- package.json
- src/components/input/multimodal/multimodalInput/multimodalInput.cy.tsx
- src/components/input/multimodal/multimodalInput/multimodalInput.stories.tsx
- src/components/input/multimodal/multimodalInput/multimodalInput.tsx
- src/components/input/multimodal/uploader/uploader.tsx
- src/components/types.ts
- Add getUploadData props to support sending additional file data
> fix(input): add getUploadData

- src/components/messageSpace/messageSpace.css
https://github.com/user-attachments/assets/2d58747f-3214-420d-a909-2b6ac9e19da9
> fix: hide scrollbar in message space

- src/components/icon/icon.tsx
- src/components/icon/index.ts
Allowing color as a prop field makes it possible to set colors from the theme
> fix(icon): update IconProps to include color and export IconProps

- src/components/dynamicForm/dynamicForm.stories.tsx
- src/components/dynamicForm/uniformsForm.tsx
- src/components/messageCanvas/messageCanvas.css
- src/components/messageCanvas/messageCanvas.tsx
- src/components/messageSpace/messageSpace.cy.tsx
- src/components/messageSpace/messageSpace.stories.tsx
- src/components/messageSpace/messageSpace.tsx
- src/components/types.ts
- Show input data in the form
- Disable form once form is submitted
- Show response sender and time in MessageCanvas
> fix(form): show input data

- package-lock.json
- package.json
-  upgrade react and react dom to the latest version
- bump the version for release
> chore: upgrade react and react dom

- src/components/input/multimodal/multimodalInput/multimodalInput.cy.tsx
- src/components/input/multimodal/multimodalInput/multimodalInput.stories.tsx
- src/components/input/multimodal/uploader/uploader.tsx
- src/components/types.ts
- update listFiles props to include url for future use
> fix(uploader): update listFiles

- src/components/index.ts
- src/components/input/multimodal/multimodalInput/multimodalInput.stories.tsx
- src/components/input/textInput/textInput.stories.tsx
- src/components/messageSpace/messageSpace.css
- src/components/messageSpace/messageSpace.cy.tsx
- src/components/messageSpace/messageSpace.stories.tsx
- src/components/messageSpace/messageSpace.tsx
- src/components/prompts/index.ts
- src/components/prompts/prompts.css
- src/components/prompts/prompts.cy.tsx
- src/components/prompts/prompts.stories.tsx
- src/components/prompts/prompts.tsx
- src/components/prompts/promptsDemo.css
- src/components/question/question.stories.tsx
- src/components/sharedDescription.ts
- src/components/types.ts
- src/rusticTheme.ts
- Add prompts component (styles are customizable.)
- Update messageSpace to display prompts
- Update theme for active state
> feat: add prompts component

- package-lock.json
- package.json
- src/components/filePreview/filePreview.css
- src/components/filePreview/filePreview.tsx
- src/components/helper.ts
- src/components/input/baseInput/baseInput.tsx
- src/components/input/multimodal/multimodalInput/multimodalInput.cy.tsx
- src/components/input/multimodal/multimodalInput/multimodalInput.stories.tsx
- src/components/input/multimodal/multimodalInput/multimodalInput.tsx
- src/components/input/multimodal/uploader/uploader.tsx
- src/components/multipart/chatCompletion/chatCompletion.stories.tsx
- src/components/multipart/chatCompletion/chatCompletion.tsx
- src/components/multipart/multipart/multipart.stories.tsx
- src/components/types.ts
- Update uploading logic: disable send button until urls are ready
- Handle special characters in the file name so that the renaming mechanism works properly
- Update storybook docs
- Show full name by default in the multimodalInput, multipart and chatCompletion components
- Add space between the download button and file name in `FilePreview`
> fix: update uploading logic

- src/components/messageSpace/messageSpace.tsx
- src/components/promptBuilder/promptBuilder.stories.tsx
- src/components/promptBuilder/promptBuilder.tsx
- src/components/prompts/prompts.tsx
- src/components/prompts/promptsDemo.css
- src/components/question/question.tsx
- src/rusticTheme.ts
- use function to generate theme
- add more button varieties
> fix: use function to generate theme

- src/components/input/multimodal/multimodalInput/multimodalInput.stories.tsx
- src/components/input/multimodal/multimodalInput/multimodalInput.tsx
- src/components/input/multimodal/uploader/uploader.tsx
- src/components/prompts/prompts.css
- src/components/prompts/prompts.tsx
- src/components/prompts/promptsDemo.css
- src/components/types.ts
- Add getUploadHeaders property to uploader and multimodalInput
- Use button instead of chip in the prompts component because the hard-coded text color won't change when theme is changed
> fix(uploader): allow adding headers in the uploader

- src/components/input/baseInput/baseInput.css
- src/components/input/baseInput/baseInput.tsx
- src/components/input/multimodal/multimodalInput/multimodalInput.cy.tsx
- src/components/input/multimodal/multimodalInput/multimodalInput.stories.tsx
- src/components/input/textInput/textInput.cy.tsx
- src/components/input/textInput/textInput.stories.tsx
- src/components/participantsContainer/index.ts
- src/components/participantsContainer/participantsContainer.cy.tsx
- src/components/participantsContainer/participantsContainer.stories.tsx
- src/components/participantsContainer/participantsContainer.tsx
- src/components/sharedDescription.ts
- src/components/types.ts
- Add mention feature (Not support rendering member's name in different styles for the first cut)
- Update storybook and tests
- The emoji menu didn't support changing selected items via keyboard. I have now added this feature for both the member menu and the emoji menu.
(Not able to use keyboard to select emoji)
https://github.com/user-attachments/assets/439c3c9b-bb29-4951-add9-3b9d1d40cf29
https://github.com/user-attachments/assets/62e3852d-95c8-4dc1-b1f5-14c134bb6036
https://github.com/user-attachments/assets/4c8a1618-2c4e-4def-8270-9836c77a9d99
> feat: add mention feature

- .storybook/main.ts
- src/components/input/multimodal/multimodalInput/multimodalInput.stories.tsx
- src/components/input/textInput/textInput.stories.tsx
> fix: try to fix emoji 404 error

- package-lock.json
- package.json
- src/components/input/baseInput/baseInput.css
- src/components/input/baseInput/baseInput.tsx
- src/components/participantsContainer/participantsContainer.stories.tsx
- src/components/participantsContainer/participantsContainer.tsx
- src/index.css
- Add avatar to participantsContainer
- Set max height for suggestion menu
> fix: add avatar to participantsContainer

- src/components/input/baseInput/baseInput.tsx
- src/components/input/emoji/emoji.tsx
- src/components/input/textInput/textInput.cy.tsx
- Use type assertion for unicode in emojiSearchResults
> fix: fix typing error

- src/components/filePreview/filePreview.tsx
- src/components/image/image.tsx
- src/components/input/baseInput/baseInput.tsx
- src/components/input/multimodal/multimodalInput/multimodalInput.tsx
- src/components/media/timeIndicator/timeIndicator.tsx
- src/components/messageCanvas/messageCanvas.cy.tsx
- src/components/messageSpace/messageSpace.cy.tsx
- src/components/messageSpace/messageSpace.tsx
- src/components/video/youtubeVideo.tsx
- src/components/visualization/chart/rechartsTimeSeries.tsx
- src/components/visualization/vegaLiteViz/vegaLiteViz.cy.tsx
- src/components/visualization/vegaLiteViz/vegaLiteViz.tsx
- Avoid using defaultProps
- Fix some warnings
> fix: avoid using defaultProps

- src/components/multipart/chatCompletion/chatCompletion.tsx
- src/components/prompts/prompts.cy.tsx
- src/components/prompts/prompts.stories.tsx
- src/components/prompts/prompts.tsx
- src/components/question/question.stories.tsx
- src/components/question/question.tsx
- Send chatCompletion message in question and prompts
- Update storybook and test
- Fix a warning in the ChatCompletion
> fix: send chatCompletion message in question and prompts

- package.json
-  remove repo url (Couldn't pass the build. Will try to add repo url later)
> fix: remove repo url

- package-lock.json
- package.json
- src/components/dynamicForm/uniformsForm.tsx
- src/components/messageSpace/messageSpace.cy.tsx
- src/components/messageSpace/messageSpace.stories.tsx
- src/components/messageSpace/messageSpace.tsx
- pass data correctly on submit
- handle inReplyTo differently
> fix(uniforms): update form data

- .storybook/addons/button/logo.tsx
- package-lock.json
- package.json
- update dragonscale logo link
> fix: update dragonscale logo link

- package-lock.json
- package.json
> chore: update release version

- src/components/visualization/vegaLiteViz/vegaLiteViz.stories.tsx
- src/components/visualization/vegaLiteViz/vegaLiteViz.tsx
- src/components/visualization/vegaLiteViz/vegaLiteViz.types.ts
- support streaming in vegaLiteViz
> fix: support streaming in vegaLiteViz
